import { chromium, expect } from '@playwright/test';
import { spawn } from 'node:child_process';
import { mkdir, readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const server=spawn(process.execPath,['scripts/serve.mjs'],{cwd:new URL('..',import.meta.url),env:{...process.env,PORT:'4185'},stdio:['ignore','pipe','pipe']});
let browser;
try {
  await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);server.once('exit',()=>reject(new Error('Test server exited')));});
  browser=await chromium.launch({headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:1080},deviceScaleFactor:1});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  const external=[];page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:4185')&&!r.url().startsWith('blob:')&&!r.url().startsWith('data:'))external.push(r.url());});
  await page.goto('http://127.0.0.1:4185');
  await expect(page.locator('#eligible-count')).toHaveText('217');
  await expect(page.locator('#company-rows tr')).toHaveCount(25);
  await expect(page.locator('#company-rows tr').first()).toContainText('Target');
  await mkdir(new URL('../test-results/',import.meta.url),{recursive:true});
  await page.screenshot({path:'test-results/observatory-desktop.png',fullPage:true});
  await page.locator('#search').fill('Microsoft');
  await expect(page.locator('#company-rows tr')).toHaveCount(1);
  await page.locator('#company-rows .company-name').click();
  await expect(page.locator('#company-dialog')).toBeVisible();
  await expect(page.locator('#dialog-content')).toContainText('Source page SHA-256');
  await page.keyboard.press('Escape');
  await expect(page.locator('#company-dialog')).not.toBeVisible();
  await page.locator('#lens').selectOption('extended');
  await expect(page.locator('#eligible-count')).toHaveText('71');
  await expect(page.locator('#company-rows tr')).toContainText('partial');
  await page.locator('#search').fill('');
  await expect(page.locator('#company-rows tr').first()).toContainText('Newmont');
  await page.locator('#sector').selectOption('Utilities');
  await page.locator('#coverage').selectOption('complete');
  await expect(page.locator('#empty')).toBeVisible();
  await page.locator('#clear-filters').click();
  await page.locator('#lens').selectOption('core');
  await page.locator('[data-tpq="5"][data-ctt="1"]').click();
  await expect(page.locator('#company-rows tr')).toHaveCount(1);
  await expect(page.locator('#company-rows tr')).toContainText('Target');
  await page.locator('#ctt-map').selectOption('25');
  await expect(page.locator('#company-rows tr')).toContainText('39.9');
  await page.locator('#clear-cell').click();
  await page.locator('#reset-weights').click();
  const boxes=page.locator('#company-rows input[type=checkbox]');
  await boxes.nth(0).check();await boxes.nth(1).check();await boxes.nth(2).check();
  await boxes.nth(3).click();
  assert.equal(await boxes.nth(3).isChecked(),false);
  await expect(page.locator('.compare-item')).toHaveCount(3);
  await page.locator('#clear-comparison').click();
  const downloads=[];page.on('download',d=>downloads.push(d));
  await page.locator('#export').click();
  await expect.poll(()=>downloads.length).toBe(2);
  const csv=downloads.find(d=>d.suggestedFilename().endsWith('.csv'));
  await csv.saveAs('test-results/export.csv');
  const csvContent=await readFile('test-results/export.csv','utf8');
  assert.equal(csvContent.split('\n').length,501);
  await page.locator('[data-view="portfolio"]').click();
  await expect(page.locator('#allocation-status')).toContainText('100% allocated');
  await expect(page.locator('#allocation-status')).toContainText('46%');
  await page.locator('#stress').selectOption('delay');
  await expect(page.locator('#stress-value')).toContainText('-16.2%');
  await page.locator('[data-allocation="ETN"]').fill('9');
  await page.locator('[data-allocation="ETN"]').press('Tab');
  await expect(page.locator('#allocation-status')).toContainText('101.0%');
  await expect(page.locator('#export-portfolio')).toBeDisabled();
  await page.locator('#reset-portfolio').click();
  await expect(page.locator('#export-portfolio')).toBeEnabled();
  await page.screenshot({path:'test-results/portfolio-desktop.png',fullPage:true});
  await page.locator('[data-view="method"]').click();
  await expect(page.locator('#view-method')).toContainText('Missingness is part of the result');
  await page.screenshot({path:'test-results/method-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.locator('[data-view="compare"]').click();
  await page.screenshot({path:'test-results/observatory-mobile.png',fullPage:true});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),'Page must not overflow mobile viewport');
  await page.locator('#search').fill('Eaton');
  await page.locator('#company-rows .company-name').click();
  await expect(page.locator('#dialog-title')).toContainText('Eaton');
  await page.locator('#close-dialog').click();
  await page.locator('[data-view="portfolio"]').click();
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));
  await page.screenshot({path:'test-results/portfolio-mobile.png',fullPage:true});
  assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
  console.log('Browser checks passed: desktop/mobile, filters, matrix, scoring, comparisons, provenance, exports, constraints, stress tests and zero external requests.');
} finally { if(browser)await browser.close();server.kill(); }
